apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: nodejs-webapp-pipeline
  name: nodejs-webapp-pipeline
spec:
  source:
    git:
      ref: master
      uri: https://github.com/techjw/cicd-demo.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic
